23 search ingredients
Van-sh/Grocery-Planner pull request #24
Opened 2024-09-14 14:40 UTC by Van-sh

- Add Search in Ingredients
- Add API_URL constant in contants.ts as a configurable API base URL value
- Fix delete modal on mobile

2024-09-14 18:06 UTC, Van-sh commented
This PR fulfills #23 and #21

2024-09-24 17:49 UTC, Van-sh commented
Fixed #18

2024-09-27 15:58 UTC, SakshiShreya requested changes

2024-09-27 15:58 UTC, SakshiShreya commented on src/constants.ts
> +export const API_URL = "https://grocery-planner-be.onrender.com"
Add new line at EOF.

2024-09-27 15:58 UTC, SakshiShreya commented on src/planner/ingredients/index.tsx
> +            <>
Remove fragment

2024-09-28 13:47 UTC, SakshiShreya approved these changes

2024-09-28 13:47 UTC, merged