38 create foods
Van-sh/Grocery-Planner pull request #41
Opened 2024-10-28 13:47 UTC by Van-sh

2025-01-12 18:37 UTC, SakshiShreya requested changes

2025-01-12 18:37 UTC, SakshiShreya commented on src/planner/dishes/createForm/index.tsx
> +// TODO: Create a dropdown for Unit
This line can be removed. Unit dropdown is already there.

2025-01-12 18:37 UTC, SakshiShreya commented on src/planner/dishes/index.tsx
> +         // refetch();
Do we not want to refetch here?

2025-01-12 20:46 UTC, Van-sh commented on src/planner/dishes/index.tsx
> +         // refetch();
we do, it's been commented out currently because get API has not been implemented into this branch

2025-01-13 17:36 UTC, SakshiShreya approved these changes

2025-01-15 04:22 UTC, merged