47: Add User menu and change password form
Van-sh/Grocery-Planner pull request #55
Opened 2024-11-30 16:58 UTC by SakshiShreya

Desktop: 
![image](https://github.com/user-attachments/assets/ed74a7f2-b2cb-4b73-8a9e-aa4393ec2f0c)

Mobile:
<img height="500" src="https://github.com/user-attachments/assets/ef34866a-11ef-4bf0-a958-e57a6c9e8525" />

2025-01-11 11:11 UTC, Van-sh requested changes

2025-01-11 11:11 UTC, Van-sh commented on src/common/auth/userMenu.tsx
> +        <DropdownItem key="profile">Profile</DropdownItem>
use different keys for siblings

2025-01-12 18:40 UTC, SakshiShreya commented on src/common/auth/userMenu.tsx
> +        <DropdownItem key="profile">Profile</DropdownItem>
Done

2025-01-13 08:23 UTC, Van-sh approved these changes

2025-01-13 17:36 UTC, merged